#!/usr/bin/env python3
"""Build PREVIEW.md — a private, GitHub-viewable rendering of the manuscript.

GitHub renders markdown text and static images but strips iframes/scripts, so
this preview embeds the *static* figure PNGs (not the interactive Plotly
versions). It exists so the team can read the manuscript inside the private
repo while the public GitHub Pages site is held back.

Regenerate after editing the Google Doc:

    python scripts/fetch_prose.py      # refresh _prose.md from the Doc
    cd analysis && uv run python make_figures.py && cd ..   # refresh figures
    python scripts/build_preview.py    # rebuild PREVIEW.md
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROSE = ROOT / "_prose.md"
OUT = ROOT / "PREVIEW.md"

TITLE = "Air sampling in team congregate spaces for early detection of respiratory virus threats"
SUBTITLE = "Viral air sampling in team settings"
AUTHORS = (
    "David Simon, Timothy Locksmith, Nick Minor, Eli J. O'Connor, "
    "Shelby L. O'Connor†, David H. O'Connor† (corresponding: dhoconno@wisc.edu)"
)

FIG1 = """
![Figure 1: respiratory-virus detections across the World Cup](analysis/figure1_static.png)

**Figure 1. Respiratory-virus detections in team-space air samples across the 2026 FIFA World Cup.**
Air was sampled continuously in Team Canada congregate spaces across five host
cities from 3 June to 4 July 2026, and every cartridge was tested for
SARS-CoV-2, influenza A, influenza B, and RSV. All cities are shown on a single
continuous local-time axis. Rows are the four target viruses; each rectangle is
one cartridge tested for one virus, drawn to its exact sampling window. Rooms
are merged within each city. A box is blue if the virus was detected in any
room (fill mapped to the lowest Ct across rooms), white if no room detected it
but at least one returned a valid negative, and grey if every room was invalid.
An asterisk beneath the axis marks a session with partial room validity.
"""

FIG2 = """
![Figure 2: per-room detections during the Houston period](analysis/figure2_houston.png)

**Figure 2. Per-room detections during the Houston sampling period.**
Sampling in Houston ran from the evening of 30 June to 4 July 2026 across four
team spaces (physiotherapy room, meal room, equipment room, and a team-occupied
hallway). Rows group the four target viruses within each room; the horizontal
axis is local wall-clock time. White boxes are valid negatives, grey boxes are
invalid runs, and blue boxes are detections (fill mapped to Ct). On 1 July,
SARS-CoV-2 was detected in the meal room, physiotherapy room, and hallway, and
influenza A in the equipment room. SARS-CoV-2 returned on 3–4 July at lower Ct,
most strongly in the meal room.
"""

FIG_S1 = """
![Online supplemental figure 1: community wastewater context by host city](analysis/figure3_wastewater.png)

**Online supplemental figure 1. Community wastewater surveillance context in each host city over the 2025–2026 respiratory season.**
Each panel (A to E) is one host city, plotting publicly reported municipal
wastewater levels for the four study targets (SARS-CoV-2, influenza A, influenza
B, and RSV) from August 2025 through mid-July 2026. The shaded gold band marks
Team Canada's air-sampling window in that city. **The four data sources report
non-interchangeable quantities and are each shown on their own independent
vertical axis; levels must be read within a panel and never compared between
panels.** Panels A–C (Montreal, Toronto, Vancouver) use the PHAC wastewater
aggregate (PMMoV-normalized index); panel D (Los Angeles) uses the California
CDPH/CDC-NWSS JWPCP dataset, self-normalized to fecal load; panel E (Houston)
uses the Rice/Houston Health Department 69th Street index (SARS-CoV-2 only,
ending 22 June 2026, before the team's stay). Across all five cities the visit
windows fall in the seasonal trough, at or near each site's own lowest values,
indicating no host city was experiencing unusually high community
respiratory-virus circulation while the team was present.
"""

BANNER = (
    "> **Private preview.** This is a static rendering of the manuscript for "
    "in-repo review while the interactive site is held back. Figures are the "
    "static (print) versions; the interactive Plotly figures appear on the "
    "GitHub Pages site once it is published. Auto-generated by "
    "`scripts/build_preview.py` — do not edit by hand; edit the Google Doc."
)


def insert_after_paragraph(prose: str, needle: str, block: str, label: str) -> str:
    """Insert `block` immediately after the paragraph that contains `needle`.

    Paragraphs are separated by blank lines. Raises if the callout is not found,
    so a Doc edit that drops or renames a figure reference fails loudly rather
    than silently placing figures in the wrong spot.
    """
    paras = prose.split("\n\n")
    for i, para in enumerate(paras):
        if needle in para:
            paras.insert(i + 1, block.strip())
            return "\n\n".join(paras)
    raise SystemExit(
        f"Could not find the {label} callout ('{needle}') in _prose.md — "
        "did the figure reference change in the Doc?"
    )


def main() -> None:
    prose = PROSE.read_text(encoding="utf-8")
    # Drop the auto-generated HTML comment header from _prose.md.
    prose = re.sub(r"<!--.*?-->\n*", "", prose, count=1, flags=re.S)
    # The Quarto anchor links don't resolve on GitHub; make them plain text.
    prose = prose.replace("[Figure 1](#fig-detections)", "Figure 1")
    prose = prose.replace("[Figure 2](#fig-houston)", "Figure 2")
    prose = prose.strip()

    # Place each figure right after the paragraph that first calls it out.
    # Figures 1 and 2 are introduced together; insert 2 first so that after
    # both insertions they end up in 1-then-2 order below that paragraph.
    prose = insert_after_paragraph(
        prose, "displayed over time in Figure 1 and Figure 2", FIG2, "Figure 2"
    )
    prose = insert_after_paragraph(
        prose, "displayed over time in Figure 1 and Figure 2", FIG1, "Figure 1"
    )
    prose = insert_after_paragraph(
        prose, "shown in online supplemental figure 1", FIG_S1,
        "online supplemental figure 1",
    )

    doc = (
        f"# {TITLE}\n\n"
        f"*{SUBTITLE}*\n\n"
        f"{AUTHORS}\n\n"
        f"† equal contribution\n\n"
        f"{BANNER}\n\n"
        "---\n\n"
        f"{prose}\n"
    )
    OUT.write_text(doc, encoding="utf-8")
    print(f"wrote {OUT} ({len(doc)} bytes)")


if __name__ == "__main__":
    main()
